---
tenant_parameters:
  - { name: loadReference, value: "true" }
  - { name: loadSample, value: "true" }

auth_required: true
enable_okapi: true
folio_install_type: single_server
update_launch_descr: true

folio_modules:
  - name: mod-pubsub
    deploy: yes
    docker_env:
      - name: KAFKA_HOST
        value: "{{ kafka_host }}"
      - name: KAFKA_PORT
        value: "{{ kafka_port }}"
      - name: OKAPI_URL
        value: "{{ okapi_url }}"
