---

 - name: launch ec2 instance
   local_action:
       module: ec2
       aws_access_key: "{{ jenkins_aws_access_key }}"
       aws_secret_key: "{{ jenkins_aws_secret_key }}"
       key_name: "{{ ec2_keypair }}"
       group_id: "{{ ec2_security_groupids }}" 
       instance_type: "{{ ec2_instance_type }}"
       image: "{{ ec2_ami }}"
       vpc_subnet_id: "{{ ec2_subnet_id }}"
       region: "{{ aws_region }}"
       instance_tags: "{{ ec2_instance_tags }}"
       assign_public_ip: yes
       #instance_profile_name: "{{ ec2_instance_profile }}"
       exact_count: "{{ ec2_exact_count }}"
       count_tag: 
          Group: "{{ ec2_group }}"
       volumes: "{{ ec2_volumes }}"
       wait: yes
       wait_timeout: 500
   register: ec2
         
 - debug: var=ec2 

 - fail:
      msg: new instance failed to launch
   when: not ec2.instance_ids

 - add_host: 
      name: "{{ item.private_ip }}"
      #groups: "{{ ec2_group }}"
      groups: "{{ ec2_hostgroups }}"
      ec2_region: "{{ aws_region }}"
      ec2_ip_address: "{{ item.public_ip }}"
      ec2_id: "{{ item.id }}"
   with_items: "{{ ec2.instances }}"

 - name: wait for instances to boot 
   wait_for: host={{item.private_ip}} port=22 delay=60 timeout=320 state=started
   with_items: "{{ ec2.instances }}"

