FROM nginx:stable-alpine

COPY output /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
{% if yarn_lock.stat.exists|default(false) %}
COPY yarn.lock /usr/share/nginx/html
{% endif %}
{% if install_json.stat.exists|default(false) %}
COPY install.json /usr/share/nginx/html
{% endif %}
