---

ec2_keypair: 'aws-sling-dev'
ec2_instance_type: 't2.small'
ec2_subnet_id: 'subnet-c8df3dbe'
ec2_ami: 'ami-e13739f6'
ec2_instance_profile: 'cloudwatch_log_agent_role'
ec2_exact_count: 1
ec2_instance_tags: '{ "Env":"ci" }'
ec2_security_groupids: ['sg-b6b7dcf']
ec2_hostgroups: "tag_Env_ci,tag_Group_{{ ec2_group }}"

ec2_volumes:
   - device_name: /dev/sda1
     volume_type: gp2
     volume_size: 30
     delete_on_termination: true

